export default {
  PLAYER_BACKPACK: 0,
  PLAYER_PRIMARY_SLOT: 1,
  MAGAZINE_POCKETS: 2,
  MEDICINE_POCKETS: 3,
  BACKPACK_SLOT: 4,

  LOOT_CONTAINER: 5,

  FACILITY: 6,
  CONSTRUCTION_SITE: 7,
  GARDEN: 8,
};
