export default {
  CONNECT_TO_HOST: 0,
  OTHER_CONNECTED_TO_HOST: 1,
  LATENCY: 2,
  DISCONNECT_FROM_HOST: 3,
  OTHER_DISCONNECT_FROM_HOST: 4,

  REQUEST_JOIN_GAME: 5,

  DATA_PLAYER_SYNC: 6,
  DATA_PLAYER_POSITION: 7,
  DATA_PLAYER_VELOCITY: 8,
  DATA_PLAYER_MOVEMENT_INPUT: 9,
  DATA_PLAYER_WEAPON_FUNCTION: 10,
  DATA_PLAYER_WEAPON_EQUIP: 11,

  REQUEST_INSTANCE_LIST: 12,
  REQUEST_FAST_TRAVEL: 13,

  REQUEST_CONTAINER_CONTENT: 14,
  START_CONTAINER_INVENTORY_STREAM: 15,
  CONTAINER_INVENTORY_STREAM: 16,
  END_CONTAINER_INVENTORY_STREAM: 17,
  CONTAINER_INVENTORY_ADD_ITEM: 18,
  CONTAINER_INVENTORY_ADD_STACK: 19,
  CONTAINER_INVENTORY_IDENTIFY_ITEM: 20,
  CONTAINER_INVENTORY_ROTATE_ITEM: 21,
  CONTAINER_INVENTORY_REMOVE_ITEM: 22,

  SERVER_ERROR: 23,
  CLIENT_ERROR: 24,
};
