export default {
  CONNECT_TO_HOST: 0,
  OTHER_CONNECTED_TO_HOST: 1,
  LATENCY: 2,
  DISCONNECT_FROM_HOST: 3,
  OTHER_DISCONNECT_FROM_HOST: 4,

  REQUEST_JOIN_GAME: 5,

  DATA_PLAYER_SYNC: 6,
  DATA_PLAYER_POSITION: 7,
  DATA_PLAYER_VELOCITY: 8,
  DATA_PLAYER_MOVEMENT_INPUT: 9,
  DATA_PLAYER_WEAPON_FUNCTION: 10,
  DATA_PLAYER_WEAPON_EQUIP: 11,

  REQUEST_INSTANCE_LIST: 12,
  REQUEST_FAST_TRAVEL: 13,

  CONTAINER_REQUEST_CONTENT: 14,
  CONTAINER_ADD_ITEM: 15,
  CONTAINER_IDENTIFY_ITEM: 16,
  CONTAINER_MOVE_AND_ROTATE_ITEM: 17,
  CONTAINER_DELETE_ITEM: 18,

  SERVER_ERROR: 19,
  CLIENT_ERROR: 20,
};
