export default {
  CONNECT_TO_HOST: 0,
  OTHER_CONNECTED_TO_HOST: 1,
  LATENCY: 2,
  DISCONNECT_FROM_HOST: 3,
  OTHER_DISCONNECT_FROM_HOST: 4,

  REQUEST_JOIN_GAME: 5,
  SYNC_WORLD_STATE: 6,

  DATA_PLAYER_SYNC: 7,
  DATA_PLAYER_POSITION: 8,
  DATA_PLAYER_VELOCITY: 9,
  DATA_PLAYER_MOVEMENT_INPUT: 10,
  DATA_PLAYER_WEAPON_FUNCTION: 11,
  DATA_PLAYER_WEAPON_EQUIP: 12,

  REQUEST_INSTANCE_LIST: 13,
  REQUEST_FAST_TRAVEL: 14,

  REQUEST_CONTAINER_CONTENT: 15,
  START_CONTAINER_INVENTORY_STREAM: 16,
  CONTAINER_INVENTORY_STREAM: 17,
  END_CONTAINER_INVENTORY_STREAM: 18,
  CONTAINER_INVENTORY_ADD_ITEM: 19,
  CONTAINER_INVENTORY_ADD_STACK: 20,
  CONTAINER_INVENTORY_IDENTIFY_ITEM: 21,
  CONTAINER_INVENTORY_ROTATE_ITEM: 22,
  CONTAINER_INVENTORY_REMOVE_ITEM: 23,

  SERVER_ERROR: 24,
  CLIENT_ERROR: 25,
};
