export default {
  ACKNOWLEDGMENT: 0,
  CONNECT_TO_HOST: 1,
  REMOTE_CONNECTED_TO_HOST: 2,
  PING: 3,
  PONG: 4,
  DISCONNECT_FROM_HOST: 5,
  REMOTE_DISCONNECT_FROM_HOST: 6,

  REQUEST_JOIN_GAME: 7,
  SYNC_WORLD_STATE: 8,
  SYNC_WORLD_STATE_WEATHER: 9,

  REQUEST_PLAYER_LIST: 10,
  DATA_PLAYER_SYNC: 11,
  PLAYER_DATA_POSITION: 12,
  DATA_PLAYER_VELOCITY: 13,
  PLAYER_DATA_MOVEMENT_INPUT: 14,
  DATA_PLAYER_WEAPON_FUNCTION: 15,
  DATA_PLAYER_WEAPON_EQUIP: 16,

  REMOTE_ENTERED_THE_INSTANCE: 17,
  REMOTE_DATA_POSITION: 18,
  REMOTE_DATA_MOVEMENT_INPUT: 19,
  REMOTE_LEFT_THE_INSTANCE: 20,
  REMOTE_RETURNED_TO_CAMP: 21,

  REQUEST_INSTANCE_LIST: 22,
  REQUEST_FAST_TRAVEL: 23,
  SYNC_INSTANCE: 24,

  REQUEST_CONTAINER_CONTENT: 25,
  START_CONTAINER_INVENTORY_STREAM: 26,
  CONTAINER_INVENTORY_STREAM: 27,
  END_CONTAINER_INVENTORY_STREAM: 28,
  CONTAINER_INVENTORY_ADD_ITEM: 29,
  CONTAINER_INVENTORY_ADD_STACK: 30,
  CONTAINER_INVENTORY_IDENTIFY_ITEM: 31,
  CONTAINER_INVENTORY_ROTATE_ITEM: 32,
  CONTAINER_INVENTORY_REMOVE_ITEM: 33,
  RELEASE_CONTAINER_CONTENT: 34,

  PATROL_STATE: 35,
  PATROLS_DATA_PROGRESS_POSITION: 36,

  REQUEST_SCOUT_LIST: 37,
  START_OPERATIONS_SCOUT_STREAM: 38,
  OPERATIONS_SCOUT_STREAM: 39,
  END_OPERATIONS_SCOUT_STREAM: 40,

  SYNC_SCOUTING_DRONE_DATA: 41,
  SCOUTING_DRONE_DATA_POSITION: 42,
  DESTROY_SCOUTING_DRONE_DATA: 43,

  INVALID_REQUEST: 44,
  SERVER_ERROR: 45,
  CLIENT_ERROR: 46,
};
