enum NETWORK_STATUS
{
	OFFLINE,
	CONNECTING,
	TIMED_OUT,
	CONNECTED,
	CONNECTED_SAVE_SELECTED,
	
	JOINING_TO_GAME,
	// NETWORK STATUS THRESHOLD FOR CERTAIN MESSAGES
	SYNC_WORLD_STATE,
	SYNC_DATA,
	SESSION_IN_PROGRESS,
	
	DISCONNECTING,
	DISCONNECTED
}